### ISSUE TITLE
TRestMetadata::GetDblParameterWithUnits issue for scientific notation

### ISSUE THREAD

**Issue by sebhoof** [rest-for-physics/framework#24]
When this function is used to extract the `value` field from an xml file, any entry such as
```
<parameter name="some_parameter" value=1.23e-4 />
```
fails because the "e" is interpreted as a unit. As a result, the parameter value in the example above would be interpreted as 1.23.

I believe the problematic part is here:
https://github.com/rest-for-physics/framework/blob/5a9f50fcf0731faaaf701eb960314a4ee1ef39cf/source/framework/tools/src/TRestSystemOfUnits.cxx#L115

**Comment by nkx111** [comment]
Hi, thanks for reporting this issue! I have fixed this problem in commit f06e426d66a03ecd79e85ddb52e1fcef43ca3563.

**Comment by sebhoof** [comment]
This seems to work for me, thanks for fixing! I removed an alternative function that I had introduced to circumvent this issue in this commit: 22d3611357eba754c332362908e2c7f9b5dc3b9e.

**Comment by jgalan** [comment]
Will the new fix still have a small leak when we use `eV` units? This is the only unit at `TRestSystemOfUnits` starting by `e`.
